package rw.mangatek.ebm2.core.enns;

public enum SettingName {
	INVOICE_NUMBER, CURRENT_TAXPAYER_TIN, CURRENT_BRANCH, CURRENT_MRC, CURRENT_DEVICE, PULL_DATE, CURRENT_TAXPAYER_NAME,
	CURRENT_TAXPAYER_ADDRESS,PURCHASE_NUMBER
}
